server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/getemployed
    username: getemployed
    password: ${DB_PASSWORD}

  mail:
    host: smtp.mail.ru
    port: 465
    username: getemployedemailsender@mail.ru
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          ssl:
            enable: true
            trust: smtp.mail.ru



  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: email-service
      auto-offset-reset: earliest
    topics:
      email-event: email-event
      password-reset-event: password-reset-event

    bootstrap-servers: localhost:9094


app:
  frontend:
    url: http://localhost:3000
    home-page-url: http://localhost:3000/verify-success
    verify-failed-url: http://localhost:3000/verify-failed
    verify-url-pattern: http://localhost:3000/verify?token=%s
    reset-url-pattern: http://localhost:3000/reset-password?token=%s
  security:
    email-token-pepper: ${EMAIL_TOKEN_PEPPER}
    email-token-ttl-minutes: 30
  verify:
    base-url: http://localhost:8080
    token-ttl-minutes: 60

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


jwt:
  secret: ${JWT_SECRET}
  ttl-minutes: 60


